# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fixit11
# "service" is the name of this project. This will also be added to your AWS resource names.
service: FixIt

build:
  esbuild:
    banner:
      js: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);"
    bundle: true
    format: esm
    platform: node
    target: node20
    external:
      - "@supabase/supabase-js"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY}
    SUPABASE_CONNECTION_STRING: ${env:SUPABASE_CONNECTION_STRING}
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi: "*"
